using './cert-binding.bicep'

// Production certificate-binding configuration. Keep this in sync with main.production.bicepparam.
param location = 'polandcentral'
param keyVaultName = 'finance-app-key-vault'
param keyVaultIdentityName = 'finance-app-secrets'
param containerRegistryServer = 'ghcr.io'
param containerRegistryUsername = 'sziszka90'
param gatewayImageTag = 'latest'
param gatewayCustomDomain = 'www.financeapp.fun'
param certificateName = 'www.financeapp.fun'
param managedEnvironmentName = 'FinanceApp'
param gatewayName = 'finance-app-gateway'
param backendName = 'finance-app-backend'
param frontendName = 'finance-app-frontend'
param llmProcessorName = 'finance-app-llmprocessor'
param projectName = 'FinanceApp'
param managedBy = 'Bicep-Template'
param costCenter = 'Finance'
param environment = 'production'
